Received: (from majordomo@localhost) by pauillac.inria.fr (8.7.6/8.7.3) id RAA12326; Wed, 2 Oct 2002 17:57:32 +0200 (MET DST)
X-Authentication-Warning: pauillac.inria.fr: majordomo set sender to owner-caml-list@pauillac.inria.fr using -f
Received: from concorde.inria.fr (concorde.inria.fr [192.93.2.39]) by pauillac.inria.fr (8.7.6/8.7.3) with ESMTP id RAA12487 for <caml-list@pauillac.inria.fr>; Wed, 2 Oct 2002 17:57:31 +0200 (MET DST)
Received: from albatross.prod.itd.earthlink.net (albatross.mail.pas.earthlink.net [207.217.120.120])
	by concorde.inria.fr (8.11.1/8.11.1) with ESMTP id g92FvU505019
	for <caml-list@inria.fr>; Wed, 2 Oct 2002 17:57:31 +0200 (MET DST)
Received: from user-0ccegbj.cable.mindspring.com ([24.199.65.115] helo=cs.cornell.edu)
	by albatross.prod.itd.earthlink.net with esmtp (Exim 3.33 #1)
	id 17wlsO-0001EG-00; Wed, 02 Oct 2002 08:57:28 -0700
Message-ID: <3D9B1767.8030902@cs.cornell.edu>
Date: Wed, 02 Oct 2002 11:57:27 -0400
From: "Yaron M. Minsky" <yminsky@CS.Cornell.EDU>
User-Agent: Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.0.1) Gecko/20020918
X-Accept-Language: en-us, en
MIME-Version: 1.0
To: Alessandro Baretta <alex@baretta.com>
CC: Ocaml <caml-list@inria.fr>
Subject: Re: [Caml-list] Uncaught exceptions (or am I going crazy?)
References: <3D9B03DF.5040806@cs.cornell.edu> <3D9B0978.E4A5D96@beaune.inria.fr> <3D9B1306.6050208@cs.cornell.edu> <3D9B18FA.80809@baretta.com>
Content-Type: text/plain; charset=us-ascii; format=flowed
Content-Transfer-Encoding: 7bit
Sender: owner-caml-list@pauillac.inria.fr
Precedence: bulk

Alessandro Baretta wrote:
> 
> 
> Yaron M. Minsky wrote:
> 
>> All the explanations given so far make sense except for one thing:  
>> they all suggest that the program should terminate.  But my program 
>> doesn't terminate, it just prints out the "Uncaught exception" string 
>> and keeps on executing.  I am not to my knowledge making any use of 
>> threads, so that odesn't seem like it should be the right explanation 
>> either.
>>
>> So, any more thoughts?
>>
>> y
> 
> 
> I noticed this. You are probably linking to a library which raises and 
> then catches the exception, printing out the error message. Oftentimes, 
> GUI libraries have this feature. This might explain why your program 
> does not terminate when the exception is raised.
> 
> Can you send in a test case that reproduces this behavior, for reference?
> 
> Alex

Unfortunately, I don't have a nice, small test case as of yet.  I'll 
send one in when I get it.  As for libraries, I'm using numerix, 
cryptokit, bigarray, unix and str.  I think that's it except for my own 
code.  It doesn't seem like any of those should be catching Sys_errors.

y

-------------------
To unsubscribe, mail caml-list-request@inria.fr Archives: http://caml.inria.fr
Bug reports: http://caml.inria.fr/bin/caml-bugs FAQ: http://caml.inria.fr/FAQ/
Beginner's list: http://groups.yahoo.com/group/ocaml_beginners

