Return-Path: <debourse@email.enst.fr>
Received: from concorde.inria.fr (concorde.inria.fr [192.93.2.39]) by pauillac.inria.fr (8.7.6/8.7.3) with ESMTP id KAA06315 for <caml-redistribution@pauillac.inria.fr>; Wed, 17 Nov 1999 10:46:52 +0100 (MET)
Received: from enst.enst.fr (enst.enst.fr [137.194.2.16])
	by concorde.inria.fr (8.8.7/8.8.7) with ESMTP id KAA23482
	for <caml-redistribution@pauillac.inria.fr>; Wed, 17 Nov 1999 10:46:52 +0100 (MET)
Received: from email.enst.fr (muse.enst.fr [137.194.2.33])
	by enst.enst.fr (8.9.1a/8.9.1) with ESMTP id KAA01018;
	Wed, 17 Nov 1999 10:46:38 +0100 (MET)
Received: from pascal.enst.fr (pascal.enst.fr [137.194.34.103])
	by email.enst.fr (8.9.3/8.9.3) with ESMTP id KAA27629;
	Wed, 17 Nov 1999 10:46:37 +0100 (MET)
Received: from localhost (debourse@localhost)
	by pascal.enst.fr (8.8.8+Sun/8.8.8) with SMTP id KAA23045;
	Wed, 17 Nov 1999 10:46:36 +0100 (MET)
Date: Wed, 17 Nov 1999 10:46:35 +0100 (MET)
From: Benoit de Boursetty <debourse@email.enst.fr>
Reply-To: Benoit.de-Boursetty@polytechnique.org
To: skaller <skaller@maxtal.com.au>
cc: caml-list@inria.fr, Pierre.Weis@inria.fr,
        caml-redistribution@pauillac.inria.fr
Subject: Re: What is this?
In-Reply-To: <3830BAC4.BBA190F7@maxtal.com.au>
Message-ID: <Pine.GSO.4.02.9911171043330.22861-100000@pascal.enst.fr>
MIME-Version: 1.0
Content-Type: TEXT/PLAIN; charset=iso-8859-1
Content-Transfer-Encoding: QUOTED-PRINTABLE
Content-Transfer-Encoding: QUOTED-PRINTABLE

On Tue, 16 Nov 1999, skaller wrote:

> Can anyone see this error?
> --------------------------------------------------------
> File "py_interp.ml", line 477, characters 6-545:
> This expression has type int but is here used with type unit
> ---------------------------------------------------------
> [exception SystemExit of int]
> .....
>
>   method run_file filename : int =
>       try
>         ignore (environment # set_attr (PyString "__name__") (PyString
> "__main__"));
>         ignore (environment # set_attr (PyString "__file__") (PyString
> filename));
>         Py_exec_module.exec_file (self:>interpreter_t)
>           (Py_exec.py_exec (self:>interpreter_t)
> (environment:>environment_t))
>           filename
>         ;
>         0
>       with
>       | SystemExit n -> n
>       | x ->
>         print_endline ("Error Near line " ^ (string_of_int (fst
> source_reference)));
>         flush stdout;
>         self#py_raise x;
>         0 (* dummy value *)
>
> -------------------------------------------------------
>
> This method is NOT called anywhere in the module.
> I cannot see where the inference engine gets the
> idea that the expression should have type unit.
>
>
> [That message is really annoying. It should read
> " .. but is used _somewhere else_ with type .."
> since it always means that. It would be nice
> to know where that somewhere else is, since half the
> time, that is where the error is]

I can't see the error, but I suggest you comment out most of the code. If
you begin with

 try
   0
 with SystemExit n -> n
  | x -> 0

and uncomment things afterwards, you can find where the problem is by
dichotomy. Since you have 6 lines of code, it shouldn't take you more than
3 tries :)

Beno=EEt de Boursetty.



